export const DEFAULT_SELECTION_HOPS = 3;
export const DEFAULT_EXPANSION_HOPS = 3;
export const DEFAULT_NODE_LABEL_FONT_SIZE_PX = 5;
export const DEFAULT_NODE_LABEL_FONT_SIZE = `${DEFAULT_NODE_LABEL_FONT_SIZE_PX}px`;
export const DEFAULT_NODE_LABEL_FONT_WEIGHT = '400';
